
import { QuizData } from './types';

export const RAW_DATA: QuizData[] = [
  {
    "capitulo": "MUSIKARIAK",
    "preguntas": [
      { "id": 1, "pregunta": "Nork abestu zuen 1. Korrikako kanta (1980koa)? (izenbururik ez duena)", "opciones": { "a": "Maite Idirinek", "b": "Xabier Amurizak", "c": "Xabier Letek", "d": "Lourdes Iriondok" }, "respuesta_correcta": "b" },
      { "id": 2, "pregunta": "Nork kantatu zuen 2. Korrikako abestia (1982koa)? (izenbururik ez duena)", "opciones": { "a": "Lou Urangak", "b": "Egan-ek taldeak", "c": "Akelarre taldeak", "d": "Idoia Urangak" }, "respuesta_correcta": "c" },
      { "id": 3, "pregunta": "Nork abestu zuen 3. Korrikako kanta (1983koa)? (izenbururik ez duena)", "opciones": { "a": "Idoia Urangak", "b": "Errobi taldeak", "c": "Lourdes Iriondok", "d": "Egan taldeak" }, "respuesta_correcta": "d" },
      { "id": 4, "pregunta": "Nork kantatu zuen 4. Korrikako abestia (1985ekoa)? (izenbururik ez duena)", "opciones": { "a": "Lontxo Aburuzak", "b": "Maite Idirinek", "c": "Errobi taldeak", "d": "Idoia Urangak" }, "respuesta_correcta": "a" },
      { "id": 5, "pregunta": "Nork abestu zuen 5. Korrikako kanta (1987koa)? (izenbururik ez duena)", "opciones": { "a": "Pantxoa eta Peio taldeak", "b": "Oskorri taldeak", "c": "Idoia Urangak", "d": "Lourdes Iriondok" }, "respuesta_correcta": "b" },
      { "id": 6, "pregunta": "Nork kantatu zuen 6. Korrikako abestia (1989koa)?", "opciones": { "a": "Xanti eta Maider taldeak", "b": "Maider eta Xabi taldeak", "c": "Xanti eta Malen taldeak", "d": "Alaitz eta Maider taldeak" }, "respuesta_correcta": "a" },
      { "id": 7, "pregunta": "Nork abestu zuen 7. Korrikako kanta (1991koa)?", "opciones": { "a": "Maixa ta Ixiar taldeak", "b": "Alaitz eta Maider taldeak", "c": "Gozategi taldeak", "d": "Irigoien anaiek eta Mikel Erramuspek" }, "respuesta_correcta": "d" },
      { "id": 8, "pregunta": "Nork kantatu zuen 8. Korrikako abestia (1993koa)?(izenbururik ez duena)", "opciones": { "a": "Negu Gorriak taldeak", "b": "Kepa Junkerak", "c": "Tapiak eta Leturia taldeak", "d": "Egan taldeak" }, "respuesta_correcta": "c" },
      { "id": 9, "pregunta": "Nork abestu zuen 9. Korrikako kanta (1995ekoa)?", "opciones": { "a": "Alaitz eta Maider taldeak", "b": "Mikel Laboak", "c": "Benito Lertxundik", "d": "Kashbad taldeak" }, "respuesta_correcta": "b" },
      { "id": 10, "pregunta": "Nork kantatu zuen 10. Korrikako abestia (1997koa)?", "opciones": { "a": "Fermin Muguruzak", "b": "Afrika Bibangek", "c": "Gozategi taldeak", "d": "Kashbad taldeak" }, "respuesta_correcta": "c" },
      { "id": 11, "pregunta": "Nork abestu zuen 11. Korrikako kanta (1999koa)?", "opciones": { "a": "Joxe Ripiau-k", "b": "Sorkun-ek", "c": "Hemendik at taldeak", "d": "Betagarri taldeak" }, "respuesta_correcta": "a" },
      { "id": 12, "pregunta": "Nork kantatu zuen 12. Korrikako abestia (2001ekoa)?", "opciones": { "a": "Etsaiak taldeak", "b": "Anari-k", "c": "Sorkun-ek", "d": "Fermin Muguruza-k" }, "respuesta_correcta": "d" },
      { "id": 13, "pregunta": "Nork abestu zuen 13. Korrikako kanta (2003koa)?", "opciones": { "a": "Berri Txarrak taldeak", "b": "Ekon-ek", "c": "Benito Lertxundik eta Xabier Letek", "d": "Mikel Laboak eta Ruper Ordorikak" }, "respuesta_correcta": "d" },
      { "id": 14, "pregunta": "Nork kantatu zuen 14. Korrikako abestia (2005ekoa)?", "opciones": { "a": "Akelarre taldeak", "b": "Afrika Bibangek", "c": "Anestesia-k", "d": "Ines Osinagak" }, "respuesta_correcta": "b" },
      { "id": 15, "pregunta": "Nork abestu zuen 15. Korrikako kanta (2007koa)?", "opciones": { "a": "Niko Etxartek eta El Drogasek", "b": "Iñigito Txapelpunk-ek", "c": "Kokein taldeak", "d": "Aiora Renteriak" }, "respuesta_correcta": "a" },
      { "id": 16, "pregunta": "Nork kantatu zuen 16. Korrikako abestia (2009koa)?", "opciones": { "a": "Willis Drummond taldeak", "b": "Betagarri taldeak", "c": "Hesian taldeak", "d": "Kerobia taldeak" }, "respuesta_correcta": "b" },
      { "id": 17, "pregunta": "Nork abestu zuen 17. Korrikako kanta (2011koa)?", "opciones": { "a": "Su ta Gar taldeak", "b": "Hesian taldeak", "c": "Gose taldeak", "d": "Gatibu taldeak" }, "respuesta_correcta": "c" },
      { "id": 18, "pregunta": "Nork kantatu zuen 18. Korrikako abestia (2013koa)?", "opciones": { "a": "Skalariak taldeak", "b": "Skakeitan taldeak", "c": "Fermin Muguruzak", "d": "Esne Beltza taldeak" }, "respuesta_correcta": "d" },
      { "id": 19, "pregunta": "Nork abestu zuen 19. Korrikako kanta (2015ekoa)?", "opciones": { "a": "Glaukoma taldeak", "b": "Ken Zazpi taldeak", "c": "Huntza taldeak", "d": "Alex Sarduik, Maixa ta Ixiar taldeak, Kepa Junkerak" }, "respuesta_correcta": "d" },
      { "id": 20, "pregunta": "Nork kantatu zuen 20. Korrikako abestia (2017koa)?", "opciones": { "a": "Izarok, Pettik, Miren Narbaizak eta Jurgi Ekizak", "b": "Izarok, Eñaut Elorrietak, Gorka Urbizuk eta Pettik.", "c": "Izarok, Pettik, Mursegok eta Jurgi Ekizak.", "d": "Izarok, Pettik, Jurgi Ekizak eta Anarik." }, "respuesta_correcta": "a" },
      { "id": 21, "pregunta": "Nork abestu zuen 21. Korrikako kanta (2019koa)?", "opciones": { "a": "Mad Muaselek, Ferminek eta La Furiak.", "b": "Olatz Salvadorrek eta Miren Narbaizak", "c": "Gorka Urbizuk eta Lide Hernandok", "d": "Leire Martinezek eta NØgen taldeak" }, "respuesta_correcta": "a" },
      { "id": 22, "pregunta": "Nork kantatu zuen 22. Korrikako abestia (2022koa)?", "opciones": { "a": "Dupla eta Joselu Anayak taldeek", "b": "Huntza eta Korrontzi taldeek", "c": "Hainbatek, besteak beste, Arabako ESIko langile taldeak.", "d": "Ane Urbizuk, Anarik eta Ane Garciak" }, "respuesta_correcta": "d" },
      { "id": 23, "pregunta": "Nork abestu zuen 23. Korrikako kanta (2024koa)?", "opciones": { "a": "Rotten XIII taldeak", "b": "Zuriñe Hidalgok", "c": "Pello Reparazek", "d": "Maite Arroitajauregik" }, "respuesta_correcta": "d" },
      { "id": 24, "pregunta": "Nork kantatuko du 24. Korrikako abestia (2026koa)?", "opciones": { "a": "Kai Nakaik eta Lide Hernandok.", "b": "Zetak-ek, Maixux Zugarramurdik, Erramun Martikorenak", "c": "ETS taldeak", "d": "Nafarroa 1512 taldeak" }, "respuesta_correcta": "b" },
      {"id":25,"pregunta":"Zein musikarik ez du oraindik Korrika abestietan parte hartu?","opciones":{"a":"Afrika Bibang-ek","b":"Tom Lizarazuk","c":"Fermin Muguruzak","d":"Ines Osinagak"},"respuesta_correcta":"b"},
      {"id":26,"pregunta":"Zein musikarik ez du oraindik Korrika abestietan parte hartu?","opciones":{"a":"Mikel Laboak","b":"La Furiak","c":"Zuriñe Hidalgok","d":"Iñigo Muguruzak"},"respuesta_correcta":"c"},
      {"id":27,"pregunta":"Zein musikarik ez du oraindik Korrika abestietan parte hartu?","opciones":{"a":"Mad Muaselek","b":"Alex Sarduik","c":"Gorka Urbizuk","d":"Izaro Andresek"},"respuesta_correcta":"c"},
      {"id":28,"pregunta":"Zein musikarik ez du oraindik Korrika abestietan parte hartu?","opciones":{"a":"Pettik","b":"Izaro Andresek","c":"Enrique Villarreal \"El Drogas\"ek","d":"Josune Arakistainek"},"respuesta_correcta":"d"},
      {"id":29,"pregunta":"Zein musikarik ez du oraindik Korrika abestietan parte hartu?","opciones":{"a":"Anarik","b":"Jurgi Ekizak","c":"Maider Zabalegik","d":"Xabi Solanok"},"respuesta_correcta":"c"},
      {"id":30,"pregunta":"Zein musikarik ez du oraindik Korrika abestietan parte hartu?","opciones":{"a":"Iñaki Ortiz de Villalbak","b":"Ixiar Orejak","c":"Ruper Ordorikak","d":"Aiora Renteriak"},"respuesta_correcta":"d"}
    ]
  },
  {
    "capitulo": "LELOAK",
    "preguntas": [
      { "id": 1, "pregunta": "Zein izan zen 1. Korrikako leloa (1980an)?", "opciones": { "a": "AEK euskararen motorra", "b": "Zuk ere esan bai euskarari", "c": "Guztiok AEKren alde", "d": "Herri bat, hizkuntza bat" }, "respuesta_correcta": "b" },
      { "id": 2, "pregunta": "Zein izan zen 2. Korrikako leloa (1982an)?", "opciones": { "a": "Euskaraz egin eta erabili", "b": "Euskara ahoan, mundu osoan", "c": "AEK, euskararen alternatiba herritarra. Korrika, herriaren erantzuna euskararen alde", "d": "Euskaraz beldurrik gabe" }, "respuesta_correcta": "c" },
      { "id": 3, "pregunta": "Zein izan zen 3. Korrikako leloa (1983an)?", "opciones": { "a": "Euskara, guztion parada", "b": "Euskara barra-barra", "c": "Nik euskaraz, zuk zergatik ez?", "d": "Euskaraz eta kitto!" }, "respuesta_correcta": "d" },
      { "id": 4, "pregunta": "Zein izan zen 4. Korrikako leloa (1985ean)?", "opciones": { "a": "Herri bat, hizkuntza bat", "b": "Euskara ezin da galdu", "c": "Euskaraz hitz egin guztiekin", "d": "Euskara kalera" }, "respuesta_correcta": "a" },
      { "id": 5, "pregunta": "Zein izan zen 5. Korrikako leloa (1987an)?", "opciones": { "a": "Euskara guztion ondarea", "b": "Euskara, zeurea", "c": "Euskara, guztiok gara", "d": "AEK aukerarik onena" }, "respuesta_correcta": "b" },
      { "id": 6, "pregunta": "Zein izan zen 6. Korrikako leloa (1989an)?", "opciones": { "a": "Euskara Korrika eta kitto Euskal Herriak AEK", "b": "Euskara, harresi guztien gainetik", "c": "Euskara ireki mundura", "d": "Mundu bat bildu" }, "respuesta_correcta": "a" },
      { "id": 7, "pregunta": "Zein izan zen 7. Korrikako leloa (1991n)?", "opciones": { "a": "AEK guztion erronka", "b": "Euskara gozatu eta partekatu", "c": "AEK guztion kalaka", "d": "Korrika euskara, euskaraz Euskal Herria" }, "respuesta_correcta": "d" },
      { "id": 8, "pregunta": "Zein izan zen 8. Korrikako leloa (1993an)?", "opciones": { "a": "Azterketa onena beldurrik ez izatea", "b": "Guztiok maite dugun hori ahoan", "c": "Denok maite dugu gure herria euskaraz", "d": "Euskararen kolorea herritarron orea" }, "respuesta_correcta": "c" },
      { "id": 9, "pregunta": "Zein izan zen 9. Korrikako leloa (1995ean)?", "opciones": { "a": "Lotsa izateari utzi", "b": "Jalgi hadi euskaraz", "c": "Beldurrik gabe, jo eta ke", "d": "Joan hadi AEKra" }, "respuesta_correcta": "b" },
      { "id": 10, "pregunta": "Zein izan zen 10. Korrikako leloa (1997an)?", "opciones": { "a": "Euskarari ekin, beti gogoarekin", "b": "Hizkuntza gogorrari, mingain zorrotza", "c": "Euskal Herria Korrika", "d": "AEK, euskararen zilborra" }, "respuesta_correcta": "c" },
      { "id": 11, "pregunta": "Zein izan zen 11. Korrikako leloa (1999an)?", "opciones": { "a": "1+1=hamaika. Zu eta ni euskaraz.", "b": "Euskarari trabarik ez, mesedez!", "c": "Euskarari ere lagundu", "d": "Euskaraz gozatu nahi dut" }, "respuesta_correcta": "a" },
      { "id": 12, "pregunta": "Zein izan zen 12. Korrikako leloa (2001ean)?", "opciones": { "a": "Gerturatu euskarara", "b": "Euskaraz hitz egiteko gertu", "c": "Herri bat gara, euskarara bildu", "d": "Mundu bat euskara bildu" }, "respuesta_correcta": "d" },
      { "id": 13, "pregunta": "Zein izan zen 13. Korrikako leloa (2003an)?", "opciones": { "a": "Mingaina zorroztu eta jendea poztu", "b": "Begirunea, euskaldunon topagunea", "c": "Elkar mugituz, emaitzak lortuz", "d": "Herri bat geroa lantzen" }, "respuesta_correcta": "d" },
      { "id": 14, "pregunta": "Zein izan zen 14. Korrikako leloa (2005ean)?", "opciones": { "a": "Euskara eraiki, maiteki", "b": "Euskal Herria euskalduntzen. Ni ere bai", "c": "Euskaraz aritzeko, jarrera ezinbesteko", "d": "Sekulako indarra euskararen deiadarra" }, "respuesta_correcta": "b" },
      { "id": 15, "pregunta": "Zein izan zen 15. Korrikako leloa (2007an)?", "opciones": { "a": "Heldu!", "b": "Euskara amaigabeko erronka", "c": "Euskara txarrena hitz egiten ez dena", "d": "Euskaraz amestuz" }, "respuesta_correcta": "a" },
      { "id": 16, "pregunta": "Zein izan zen 16. Korrikako leloa (2009an)?", "opciones": { "a": "Euskarari eutsi eta ez etsi", "b": "Ongi etorri euskaraz bizi nahi dugunon herrira", "c": "Mingainari eragin, guztiok elkarrekin", "d": "Hizkuntza ohitura, denon aztura" }, "respuesta_correcta": "b" },
      { "id": 17, "pregunta": "Zein izan zen 17. Korrikako leloa (2011n)?", "opciones": { "a": "Jalgi hadi kalera", "b": "Ongi etorri, euskararen mundura", "c": "Maitatu, ikasi, ari…Euskalakari", "d": "Heldu euskarari eta eman elkarri" }, "respuesta_correcta": "c" },
      { "id": 18, "pregunta": "Zein izan zen 18. Korrikako leloa (2013an)?", "opciones": { "a": "Euskara Herria", "b": "Euskara bultzatu, mihiari eraginez", "c": "Euskara, zazpiak bat", "d": "Eman euskara elkarri" }, "respuesta_correcta": "d" },
      { "id": 19, "pregunta": "Zein izan zen 19. Korrikako leloa (2015ean)?", "opciones": { "a": "Eman euskara elkarri", "b": "Euskara errespetu ala hil", "c": "Euskara piztu kalean", "d": "Euskahaldun" }, "respuesta_correcta": "d" },
      { "id": 20, "pregunta": "Zein izan zen 20. Korrikako leloa (2017an)?", "opciones": { "a": "Bat Zuk", "b": "Bat egin AEKrekin", "c": "Zuk eta nik, bat eginik!", "d": "Euskararen erronka, guztiona" }, "respuesta_correcta": "a" },
      { "id": 21, "pregunta": "Zein izan zen 21. Korrikako leloa (2019an)?", "opciones": { "a": "Klika.", "b": "Euskaraz bizi nahi dut", "c": "Zaindu maite duzun hori", "d": "Non Korrika, han AEK" }, "respuesta_correcta": "a" },
      { "id": 22, "pregunta": "Zein izan zen 22. Korrikako leloa (2022an)?", "opciones": { "a": "Nik euskaraz! Zuk zergatik ez?", "b": "Euskalakari", "c": "Euskaraz 365 egun", "d": "HitzEkin" }, "respuesta_correcta": "d" },
      { "id": 23, "pregunta": "Zein izan zen 23. Korrikako leloa (2024an)?", "opciones": { "a": "Gehiago, gehiagorekin gehiagotan", "b": "Euskara buruan eta ibili munduan", "c": "Herri harrotasuna", "d": "Harro Herri" }, "respuesta_correcta": "d" },
      { "id": 24, "pregunta": "Zein izango da 24. Korrikako leloa (2026an)?", "opciones": { "a": "AEK, euskaren laguna", "b": "Euskara gara", "c": "Harro herri", "d": "Euskara heriotza arriskuan" }, "respuesta_correcta": "b" }
    ]
  },
  {
    "capitulo": "ABESTIAK",
    "preguntas": [
      { "id": 1, "pregunta": "Nork abestu zuen 1. Korrikako kanta (1980koa)? (izenbururik ez duena)", "opciones": { "a": "Maite Idirinek", "b": "Xabier Amurizak", "c": "Xabier Letek", "d": "Lourdes Iriondok" }, "respuesta_correcta": "b" },
      { "id": 2, "pregunta": "Nork kantatu zuen 2. Korrikako abestia (1982koa)? (izenbururik ez duena)", "opciones": { "a": "Lou Urangak", "b": "Egan taldeak", "c": "Akelarre taldeak", "d": "Idoia Urangak" }, "respuesta_correcta": "c" },
      { "id": 3, "pregunta": "Nork abestu zuen 3. Korrikako kanta (1983koa)? (izenbururik ez duena)", "opciones": { "a": "Idoia Urangak", "b": "Itoiz taldeak", "c": "Lourdes Iriondok", "d": "Egan taldeak" }, "respuesta_correcta": "d" },
      { "id": 4, "pregunta": "Nork kantatu zituen 4. Korrikako bertsoak (1985ekoa)? (izenbururik ez duena)", "opciones": { "a": "Lontxo Aburuzak", "b": "Errobi taldeak", "c": "Maite Idirinek", "d": "Idoia Urangak" }, "respuesta_correcta": "a" },
      { "id": 5, "pregunta": "Nork abestu zuen 5. Korrikako kanta (1987koa) (izenbururik ez duena)? (izenbururik ez duena)", "opciones": { "a": "Pantxoa eta Peio taldeak", "b": "Oskorri taldeak", "c": "Idoia Urangak", "d": "Lourdes Iriondok" }, "respuesta_correcta": "b" },
      { "id": 6, "pregunta": "Zein izan zen 6. Korrikako kanta?", "opciones": { "a": "Gu AEK-koak gara!", "b": "AEK eta kito!", "c": "AEK onena!", "d": "Gora AEK!" }, "respuesta_correcta": "a" },
      { "id": 7, "pregunta": "Nork kantatu zuen 8. Korrikako abestia (1991koa)?", "opciones": { "a": "Alaitz eta Maider taldeak", "b": "Maixa eta Ixiar taldeak", "c": "Gozategi taldeak", "d": "Irigoien anaiek eta Mikel Erramuspek" }, "respuesta_correcta": "d" },
      { "id": 8, "pregunta": "Zein izan zen 8. Korrikako kanta?", "opciones": { "a": "Korrika urteko onena", "b": "Gora Korrika", "c": "Aide Korrika", "d": "Korrika eta kito!" }, "respuesta_correcta": "c" },
      { "id": 9, "pregunta": "Zein izan zen 9. Korrikako kanta?", "opciones": { "a": "Aide Korrika", "b": "Bizi ganoraz", "c": "Euskal Herria Korrika", "d": "Korrika eta kito!" }, "respuesta_correcta": "b" },
      { "id": 10, "pregunta": "Zein izan zen 10. Korrikako kanta?", "opciones": { "a": "Gora Korrika", "b": "Aide Korrika", "c": "Euskal Herria Korrika", "d": "Korrika eta AEK, a zer parea!" }, "respuesta_correcta": "c" },
      { "id": 11, "pregunta": "Zein izan zen 11. Korrikako kanta?", "opciones": { "a": "1+1=hamaika. Zu eta ni euskaraz", "b": "Big Beñat", "c": "Euskal Herria Korrika", "d": "Aide Korrika" }, "respuesta_correcta": "a" },
      { "id": 12, "pregunta": "Zein izan zen 12. Korrikako kanta?", "opciones": { "a": "Ni ere bai", "b": "Euskal Herria Korrika", "c": "Ni ere bai", "d": "Big Beñat" }, "respuesta_correcta": "d" },
      { "id": 13, "pregunta": "Zein izan zen 13. Korrikako kanta?", "opciones": { "a": "Euskal Herria Korrika", "b": "Big Beñat", "c": "Ni ere bai", "d": "Gero bat gaurdanik" }, "respuesta_correcta": "d" },
      { "id": 14, "pregunta": "Zein izan zen 14. Korrikako kanta?", "opciones": { "a": "Baita ni ere", "b": "Ni ere bai", "c": "Euskal Herria Korrika", "d": "Aide Korrika" }, "respuesta_correcta": "b" },
      { "id": 15, "pregunta": "Zein izan zen 15. Korrikako kanta?", "opciones": { "a": "Heldu", "b": "Eutsi", "c": "Erdu", "d": "Jalgi" }, "respuesta_correcta": "a" },
      { "id": 16, "pregunta": "Zein izan zen 16. Korrikako kanta?", "opciones": { "a": "Euskal Herria euskaldun", "b": "Ongi etorri lagun", "c": "Etorri lagun", "d": "Guztiok euskaldun" }, "respuesta_correcta": "b" },
      { "id": 17, "pregunta": "Zein izan zen 17. Korrikako kanta?", "opciones": { "a": "Doakotasuna helburu", "b": "Urratsez urrats normalizaziorantz", "c": "Pausoz pauso euskalakari", "d": "Euskalakariak munduan zehar" }, "respuesta_correcta": "c" },
      { "id": 18, "pregunta": "Zein izan zen 18. Korrikako kanta?", "opciones": { "a": "Guztiok batera", "b": "Bagatoz", "c": "Goazen!", "d": "Bagoaz" }, "respuesta_correcta": "d" },
      { "id": 19, "pregunta": "Zein izan zen 19. Korrikako kanta?", "opciones": { "a": "Denok kalera", "b": "Izena eman AEKn", "c": "Korrika kalera", "d": "Denok Korrikara" }, "respuesta_correcta": "d" },
      { "id": 20, "pregunta": "Zein izan zen 20. Korrikako kanta?", "opciones": { "a": "Zirkorrika", "b": "Korrikaren zirkua", "c": "Guztiok Korrika", "d": "Karrika Korrika" }, "respuesta_correcta": "a" },
      { "id": 21, "pregunta": "Zein izan zen 21. Korrikako kanta?", "opciones": { "a": "Klika Korrika.", "b": "Harro Herri", "c": "Bagoaz", "d": "Zirkorrika" }, "respuesta_correcta": "a" },
      { "id": 22, "pregunta": "Zein izan zen 22. Korrikako kanta?", "opciones": { "a": "Zirkorrika", "b": "Heldu", "c": "Klika", "d": "HitzEkin" }, "respuesta_correcta": "d" },
      { "id": 23, "pregunta": "Zein izan zen 23. Korrikako kanta?", "opciones": { "a": "Herri bat gara", "b": "Gu gara Korrika", "c": "Euskara Gara", "d": "Harro Herri" }, "respuesta_correcta": "d" },
      { "id": 24, "pregunta": "Zein da 24. Korrikako kanta?", "opciones": { "a": "Kaka Korrika", "b": "Xiberutikan Mendebaldera", "c": "Zuberotik munduko hiriburura", "d": "Klika Korrika" }, "respuesta_correcta": "b" },
      {"id":25,"pregunta":"Zein Korrikatarako egin zuten “Gero bat gaurdanik” abestia?","opciones":{"a":"12. Korrikarako","b":"13. Korrikarako","c":"11. Korrikarako","d":"14. Korrikarako"},"respuesta_correcta":"b"},
      {"id":26,"pregunta":"Zein Korrikatarako egin zuten “Txis pun, Korrika” abestia?","opciones":{"a":"17. Korrikarako","b":"12. Korrikarako","c":"13. Korrikarako","d":"15. Korrikarako"},"respuesta_correcta":"d"},
      {"id":27,"pregunta":"Zein Korrikatarako egin zuten “Big Beñat” abestia?","opciones":{"a":"12. Korrikarako","b":"13. Korrikarako","c":"9. Korrikarako","d":"10. Korrikarako"},"respuesta_correcta":"a"},
      {"id":28,"pregunta":"Zein Korrikatarako egin zuten “Zirkorrika” abestia?","opciones":{"a":"18. Korrikarako","b":"20. Korrikarako","c":"19. Korrikarako","d":"21. Korrikarako"},"respuesta_correcta":"b"},
      {"id":29,"pregunta":"Zein Korrikatarako egin zuten “Ongi etorri lagun” abestia?","opciones":{"a":"18. Korrikarako","b":"17. Korrikarako","c":"16. Korrikarako","d":"15. Korrikarako"},"respuesta_correcta":"c"},
      {"id":30,"pregunta":"Zein Korrikatarako egin zuten “Euskal Herria Korrika” abestia?","opciones":{"a":"8. Korrikarako","b":"9. Korrikarako","c":"10. Korrikarako","d":"11. Korrikarako"},"respuesta_correcta":"c"}
    ]
  },
  {
    "capitulo": "OMENDUAK",
    "preguntas": [
      { "id": 1, "pregunta": "Nor omendu zuten 1. edizioan (1980an)?", "opciones": { "a": "Rikardo Arregi Aranburu", "b": "Xabier Peña Albizu", "c": "Euskal Eskola Publikoa", "d": "Ikastolak" }, "respuesta_correcta": "b" },
      { "id": 2, "pregunta": "Nor omendu zuten 2. edizioan (1982an)?", "opciones": { "a": "Gabriel Aresti Segurola", "b": "Ramon Saizarbitoria", "c": "Rikardo Arregi Aranburu", "d": "Carlos Garaikoetxea lehendakaria" }, "respuesta_correcta": "c" },
      { "id": 3, "pregunta": "Nor omendu zuten 3. edizioan (1983an)?", "opciones": { "a": "Ramon Saizarbitoria", "b": "Xabier Lete", "c": "Mikel Laboa", "d": "Gabriel Aresti Segurola" }, "respuesta_correcta": "d" },
      { "id": 4, "pregunta": "Nor omendu zuten 4. edizioan (1985ean)?", "opciones": { "a": "Piarres Lafitte", "b": "Piarres Larzabal", "c": "Jean Luis Davant", "d": "Luis Arana" }, "respuesta_correcta": "a" },
      { "id": 5, "pregunta": "Nor omendu zuten 5. edizioan (1987an)?", "opciones": { "a": "Jon Azpillaga", "b": "Balendin Enbeita Goiria", "c": "Jon Lopategi", "d": "Jon Mugartegi" }, "respuesta_correcta": "b" },
      { "id": 6, "pregunta": "Nor omendu zuten 6. edizioan (1989an)?", "opciones": { "a": "Joxe Miel Barandiaran", "b": "Manuel Lekuona", "c": "Agustin Zumalabe", "d": "Jesus Altuna" }, "respuesta_correcta": "a" },
      { "id": 7, "pregunta": "Nor omendu zuten 7. edizioan (1991n)?", "opciones": { "a": "Nora Aurrekoetxea", "b": "Rosa Valverde Lamsfus", "c": "Nestor Basterretxea", "d": "Remigio Mendiburu Miranda" }, "respuesta_correcta": "d" },
      { "id": 8, "pregunta": "Nor omendu zuten 8. edizioan (1993an)?", "opciones": { "a": "Kike Amonarriz", "b": "Aita Luis Villasante", "c": "Martin Ugalde Orradre", "d": "Pedro Miguel Echenique" }, "respuesta_correcta": "c" },
      { "id": 9, "pregunta": "Nor omendu zuten 9. edizioan (1995ean)?", "opciones": { "a": "Lourdes Iriondo", "b": "Mikel Laboa", "c": "Benito Lertxundi", "d": "Xabier Lete" }, "respuesta_correcta": "b" },
      { "id": 10, "pregunta": "Nor omendu zuten 10. edizioan (1997an)?", "opciones": { "a": "Eduardo Chillida", "b": "Jorge Oteiza", "c": "Aita Luis Villasante", "d": "Joxe Miel Barandiaran" }, "respuesta_correcta": "c" },
      { "id": 11, "pregunta": "Nor omendu zuten 11. edizioan (1999an)?", "opciones": { "a": "Besteak beste, Gasteizko Mendia Optika", "b": "Besteak beste, Athletic", "c": "Besteak beste, Bertsozale Elkartea", "d": "Besteak beste, Arabako ESIa" }, "respuesta_correcta": "a" },
      { "id": 12, "pregunta": "Nor omendu zuten 12. edizioan (2001ean)?", "opciones": { "a": "Euskal Herriko Selekzioa", "b": "Gara egunkaria", "c": "Euskaldunon Egunkaria", "d": "Euskal Herriko Bertsozale Elkartea" }, "respuesta_correcta": "d" },
      { "id": 13, "pregunta": "Nor omendu zuten 13. edizioan (2003an)?", "opciones": { "a": "Beste euskaltegiak", "b": "Euskal eskola publikoak", "c": "Ikastolak", "d": "Ez dok amairu" }, "respuesta_correcta": "d" },
      { "id": 14, "pregunta": "Nor omendu zuten 14. edizioan (2005ean)?", "opciones": { "a": "Itxaro Borda", "b": "Andolin Eguzkitza irakaslea", "c": "Gorka Knörr", "d": "Miren Lourdes Oñederra" }, "respuesta_correcta": "b" },
      { "id": 15, "pregunta": "Nor omendu zuten 15. edizioan (2007an)?", "opciones": { "a": "Euskal Emakumea", "b": "Euskal komunikabideak", "c": "Euskal baserriak", "d": "Euskara irakasleak" }, "respuesta_correcta": "a" },
      { "id": 16, "pregunta": "Nor omendu zuten 16. edizioan (2009an)?", "opciones": { "a": "ETB", "b": "Euskara ikasi edo berreskuratu duten familiak", "c": "Euskal diaspora", "d": "Euskal trikitilariak" }, "respuesta_correcta": "b" },
      { "id": 17, "pregunta": "Nor omendu zuten 17. edizioan (2011n)?", "opciones": { "a": "IVAP", "b": "HABE", "c": "Euskaltzaindia", "d": "Udal euskaltegiak" }, "respuesta_correcta": "c" },
      { "id": 18, "pregunta": "Nor omendu zuten 18. edizioan (2013an)?", "opciones": { "a": "Fermin Muguruza", "b": "Pirritx Porrotx eta Mari Motots", "c": "Euskara irakasleak", "d": "Euskara ikasleak" }, "respuesta_correcta": "d" },
      { "id": 19, "pregunta": "Nor omendu zuten 19. edizioan (2015ean)?", "opciones": { "a": "Elhuyar", "b": "Euskaltzaindia", "c": "Eusko Jaurlaritza", "d": "Durangoko Azoka" }, "respuesta_correcta": "d" },
      { "id": 20, "pregunta": "Nor omendu zuten 20. edizioan (2017an)?", "opciones": { "a": "Korrikaren sortzaileak", "b": "Euskal idazleak", "c": "Euskal komunikabideak", "d": "Euskaldunon Egunkaria" }, "respuesta_correcta": "a" },
      { "id": 21, "pregunta": "Nor omendu zuten 21. edizioan (2019an)?", "opciones": { "a": "Txillardegi", "b": "Alaves", "c": "Berria Egunkaria", "d": "Arabako ESIko Euskara Zerbitzua" }, "respuesta_correcta": "a" },
      { "id": 22, "pregunta": "Nor omendu zuten 22. edizioan (2022an)?", "opciones": { "a": "Txirri, Mirri eta Txiribiton", "b": "Kixki ta Mizki ta Kaxkamelon", "c": "Potx eta Lotx", "d": "Pirritx, Porrotx eta Mari Motots" }, "respuesta_correcta": "d" },
      { "id": 23, "pregunta": "Nor omendu zuten 23. edizioan (2024an)?", "opciones": { "a": "Itxaro Borda", "b": "Zuriñe Hidalgo", "c": "Pello Reparaz", "d": "Azterketak Euskaraz kolektiboa" }, "respuesta_correcta": "d" },
      { "id": 24, "pregunta": "Nor omenduko dute 24. edizioan (2026an)?", "opciones": { "a": "IVAP", "b": "Errigora", "c": "HABE", "d": "Gure Zirkua" }, "respuesta_correcta": "b" },
      {"id":25,"pregunta":"Nor edo zein elkarte ez zuten omendu 11. edizioan (1999an)?","opciones":{"a":"Jose Luis Arkonada","b":"Pedro Etxenike","c":"Jose Angel Iribar","d":"Maitane Araguas"},"respuesta_correcta":"a"},
      {"id":26,"pregunta":"Nor edo zein elkarte ez zuten omendu 11. edizioan (1999an)?","opciones":{"a":"Maiatz elkartea","b":"Mendia Optika","c":"Goya gozotegia","d":"Euskalerria irratia"},"respuesta_correcta":"c"},
      {"id":27,"pregunta":"Nor edo zein elkarte ez zuten omendu 11. edizioan (1999an)?","opciones":{"a":"Etxepe enpresa","b":"CAF enpresa","c":"Mila Etxezarraga","d":"Maite Larizgoitia"},"respuesta_correcta":"b"},
      {"id":28,"pregunta":"Nor edo zein elkarte ez zuten omendu 11. edizioan (1999an)?","opciones":{"a":"Arantza herria","b":"Joserra Etxeberria","c":"Marije Learreta","d":"Ondarroa herria"},"respuesta_correcta":"d"},
      {"id":29,"pregunta":"Zein ediziotan omendu zituzten euskara ikasi eta berreskuratu duten familiak?","opciones":{"a":"14. edizioan","b":"15. edizioan","c":"16. edizioan","d":"17. edizioan"},"respuesta_correcta":"c"},
      {"id":30,"pregunta":"Zein ediziotan omendu zituzten Korrikaren sortzaileak?","opciones":{"a":"10. edizioan","b":"15. edizioan","c":"20. edizioan","d":"5. edizioan"},"respuesta_correcta":"c"}
    ]
  },
  {
    "capitulo": "HISTORIA",
    "preguntas": [
      { "id": 1, "pregunta": "Zein ediziotan galdu zen mezua?", "opciones": { "a": "Ez da inoiz galdu", "b": "1.ean", "c": "2.ean", "d": "3.ean" }, "respuesta_correcta": "b" },
      { "id": 2, "pregunta": "Zerezkoa da lekukoa?", "opciones": { "a": "Altzairuzkoa", "b": "Kanpotik egurrezkoa, barrutik metalezkoa", "c": "Egurrezkoa", "d": "Kanpotik egurrezkoa, barrutik aluminiozkoa" }, "respuesta_correcta": "c" },
      { "id": 3, "pregunta": "Lau Korrika ikusteko zenbat urte igaro behar dira?", "opciones": { "a": "Edizioa zein den", "b": "Hamar", "c": "Zortzi", "d": "Sei" }, "respuesta_correcta": "d" },
      { "id": 4, "pregunta": "Zenbat kilometro egiten dira Korrikan gutxi gorabehera?", "opciones": { "a": "2.100 inguru", "b": "3.500 inguru", "c": "1.500 inguru", "d": "3.000 inguru" }, "respuesta_correcta": "a" },
      { "id": 5, "pregunta": "Zenbat Korrika amaitu ziren Baionan?", "opciones": { "a": "Bi", "b": "Hiru", "c": "Lau", "d": "Bakarra" }, "respuesta_correcta": "c" },
      { "id": 6, "pregunta": "Non ez da inoiz amaitu Korrika?", "opciones": { "a": "Donibane Garazin", "b": "Gasteizen", "c": "Baionan", "d": "Bilbo" }, "respuesta_correcta": "a" },
      { "id": 7, "pregunta": "Zenbat Korrika egin ziren XX. mendean?", "opciones": { "a": "9", "b": "12", "c": "10", "d": "11" }, "respuesta_correcta": "d" },
      { "id": 8, "pregunta": "Non ez da inoiz hasi Korrika?", "opciones": { "a": "Orreagan", "b": "Trebiñun", "c": "Azpeitian", "d": "Amurrion" }, "respuesta_correcta": "c" },
      { "id": 9, "pregunta": "Zein urtetan jarri zen martxan Korrika kulturala?", "opciones": { "a": "2001ean, 12. edizioan", "b": "1999an, 11. edizioan", "c": "1995ean, 10. edizioan", "d": "1997an, 10. edizioan" }, "respuesta_correcta": "b" },
      { "id": 10, "pregunta": "Nola du izena Korrikaren ibilbidea azaltzen duen aplikazioak?", "opciones": { "a": "Korrika ibil bedi", "b": "Korrika ibilbidea", "c": "AEK Korrika", "d": "Korrika AEK" }, "respuesta_correcta": "c" },
      { "id": 11, "pregunta": "Zer gertatu zen lehenengo edizioa bukatu eta hurrengo egunean?", "opciones": { "a": "John Lennon tirokatu zuten.", "b": "Realak lehen liga irabazi zuen.", "c": "Fermin Muguruza jaio zen.", "d": "Life of Brian estreinatu zen zinema aretoetan." }, "respuesta_correcta": "a" },
      { "id": 12, "pregunta": "Zein urtetan ez zen ospatu Korrika?", "opciones": { "a": "2022an", "b": "1980an", "c": "2020an", "d": "2021ean" }, "respuesta_correcta": "d" },
      { "id": 13, "pregunta": "2007ko edizioan, ibilbidea eteteko zorian egon zen ibai batek gainezka egin zuelako. Zein?", "opciones": { "a": "Zadorra", "b": "Bidasoa", "c": "Ibaizabal", "d": "Ebro" }, "respuesta_correcta": "d" },
      { "id": 14, "pregunta": "Zein urtetan antolatu ziren diasporaren lehenengo Korrikak?", "opciones": { "a": "1997an", "b": "1999an", "c": "2001ean", "d": "1995ean" }, "respuesta_correcta": "b" },
      { "id": 15, "pregunta": "2011n, Euskaltzaindia omendu zuten. Noiz sortu zen?", "opciones": { "a": "1918an", "b": "1925ean", "c": "1921ean", "d": "1915ean" }, "respuesta_correcta": "a" },
      { "id": 16, "pregunta": "Nork idatzi zuen 22. edizioko mezua?", "opciones": { "a": "Onintza Enbeitak", "b": "Karmele Jaiok", "c": "Jon Arretxek", "d": "Harkaitz Canok" }, "respuesta_correcta": "b" },
      { "id": 17, "pregunta": "Nongo alkateak egin zuen estropezu lekukoa zeramala 23. edizioan?", "opciones": { "a": "Azpeitiko alkateak", "b": "Azkoitiko alkateak", "c": "Ermuko alkateak", "d": "Hermuko alkateak" }, "respuesta_correcta": "b" },
      { "id": 18, "pregunta": "2007ko edizioan zein mendate igo behar izan zuten oinez, elurteagatik?", "opciones": { "a": "Barazar", "b": "Herrera", "c": "Opakua", "d": "Urizaharra" }, "respuesta_correcta": "d" },
      { "id": 19, "pregunta": "Nork idatzi zuen 23. edizioko mezua?", "opciones": { "a": "Kepa Errastik", "b": "Kike Amonarrizek", "c": "Onintza Enbeitak", "d": "Garazi Arrulak" }, "respuesta_correcta": "d" },
      { "id": 20, "pregunta": "Non dago jatorrizko lekukoa?", "opciones": { "a": "San Telmo museoan", "b": "Guggenheim museoan", "c": "Euskararen Etxean", "d": "Izaskun Arrue kulturgunean" }, "respuesta_correcta": "a" },
      { "id": 21, "pregunta": "Zenbatgarren edizioa atzeratu behar izan zen COVIDa zela eta?", "opciones": { "a": "19. edizioa.", "b": "20. edizioa", "c": "21. edizioa", "d": "22. edizioa" }, "respuesta_correcta": "d" },
      { "id": 22, "pregunta": "Nork idatzi zuen 19. edizioko mezua?", "opciones": { "a": "Eñaut Elorrietak", "b": "Joseba Sarrionandiak", "c": "Estitxu Fernandezek", "d": "Lorea Agirrek" }, "respuesta_correcta": "d" },
      { "id": 23, "pregunta": "Nork eraman zuen lehen aldiz lekukoa?", "opciones": { "a": "AEK-ko ikasle talde batek", "b": "Martin Ugaldek", "c": "Jose Mari Satrustegi akademikoak", "d": "Ramon Labayenek" }, "respuesta_correcta": "c" },
      { "id": 24, "pregunta": "Nork eramaten du lekukoa azken kilometroan?", "opciones": { "a": "Zozketa bidez erabakitzen da", "b": "AEK-ko Batzorde Nazionalak", "c": "Korrika laguntzaileen artean zozkatzen da", "d": "Eusko Jaurlaritzako Kultura sailburuak" }, "respuesta_correcta": "b" },
      {"id":25,"pregunta":"Zenbatgarren kilometroa egin zuen Lehendakariak 12. Korrikan?","opciones":{"a":"Lehengoa","b":"Bigarrena","c":"Ehungarrena","d":"Azkenaurrekoa"},"respuesta_correcta":"b"},
      {"id":26,"pregunta":"Noiz hasi zen Korrika laguntzailea egiten?","opciones":{"a":"10. edizioan","b":"11. edizioan","c":"13. edizioan","d":"15. edizioan"},"respuesta_correcta":"c"},
      {"id":27,"pregunta":"Zenbatgarren Korrikan izan zituzten arazoak Iruñean sartzeko?","opciones":{"a":"8. Korrikan","b":"10. Korrikan","c":"13. Korrikan","d":"15. Korrikan"},"respuesta_correcta":"c"},
      {"id":28,"pregunta":"Zein ediziotarako prestatu zuten -Bidaia intimoak- dokumentala?","opciones":{"a":"13. Korrikarako","b":"14. Korrikarako","c":"15. Korrikarako","d":"16. Korrikarako"},"respuesta_correcta":"d"},
      {"id":29,"pregunta":"Zenbatgarren Korrikan prestatu zuten mezua Xabier eta Miren Amurizak?","opciones":{"a":"15. Korrikan","b":"14. Korrikan","c":"13. Korrikan","d":"12. Korrikan"},"respuesta_correcta":"a"},
      {"id":30,"pregunta":"Zein urtetan sinatu zuten bakea AEK-k eta Eusko Jaurlaritzak?","opciones":{"a":"1993an","b":"1995ean","c":"1997an","d":"1999an"},"respuesta_correcta":"c"}
  ]
  },
  {
    "capitulo": "HASIERA-BUKAERAK",
    "preguntas": [
      { "id": 1, "pregunta": "1. edizioa (1980an)?", "opciones": { "a": "Gasteiz-Gares", "b": "Oñati-Bilbo", "c": "Bilbo-Oñati", "d": "Iruñea-Donostia" }, "respuesta_correcta": "b" },
      { "id": 2, "pregunta": "2. edizioa (1982an)?", "opciones": { "a": "Baiona-Bilbo", "b": "Donostia-Iruñea", "c": "Iruñea-Donostia", "d": "Oñati-Bilbo" }, "respuesta_correcta": "c" },
      { "id": 3, "pregunta": "3. edizioa (1983an)?", "opciones": { "a": "Gasteiz-Baiona", "b": "Iruñea-Donostia", "c": "Hendaia-Bilbo", "d": "Baiona-Bilbo" }, "respuesta_correcta": "d" },
      { "id": 4, "pregunta": "4. edizioa (1985ean)?", "opciones": { "a": "Atharratze-Iruñea", "b": "Iruñea-Bilbo", "c": "Oñati-Bilbo", "d": "Baiona-Bilbo" }, "respuesta_correcta": "a" },
      { "id": 5, "pregunta": "5. edizioa (1987an)?", "opciones": { "a": "Baiona-Bilbo", "b": "Hendaia-Bilbo", "c": "Gasteiz-Baiona", "d": "Iruñea-Donostia" }, "respuesta_correcta": "b" },
      { "id": 6, "pregunta": "6. edizioa (1989an)?", "opciones": { "a": "Iruñea-Donostia", "b": "Atharratze-Iruñea", "c": "Hendaia-Bilbo", "d": "Baiona-Bilbo" }, "respuesta_correcta": "a" },
      { "id": 7, "pregunta": "7. edizioa (1991n)?", "opciones": { "a": "Baiona-Bilbo", "b": "Hendaia-Bilbo", "c": "Iruñea-Donostia", "d": "Gasteiz-Baiona" }, "respuesta_correcta": "d" },
      { "id": 8, "pregunta": "8. edizioa (1993an)?", "opciones": { "a": "Donibane Garazi-Gasteiz", "b": "Iruñea-Donostia", "c": "Iruñea-Bilbo", "d": "Gasteiz-Baiona" }, "respuesta_correcta": "c" },
      { "id": 9, "pregunta": "9. edizioa (1995ean)?", "opciones": { "a": "Atharratze-Iruñea", "b": "Donibane Garazi-Gasteiz", "c": "Gasteiz-Baiona", "d": "Arantzazu-Bilbo" }, "respuesta_correcta": "b" },
      { "id": 10, "pregunta": "10. edizioa (1997an)?", "opciones": { "a": "Donibane Garazi-Gasteiz", "b": "Maule-Iruñea", "c": "Arantzazu-Bilbo", "d": "Iruñea-Bilbo" }, "respuesta_correcta": "c" },
      { "id": 11, "pregunta": "11. edizioa (1999an)?", "opciones": { "a": "Iruñea-Donostia", "b": "Karrantza-Iruñea", "c": "Orreaga-Bilbo", "d": "Maule-Iruñea" }, "respuesta_correcta": "a" },
      { "id": 12, "pregunta": "12. edizioa (2001ean)?", "opciones": { "a": "Iruñea-Donostia", "b": "Maule-Iruñea", "c": "Orreaga-Bilbo", "d": "Gasteiz-Baiona" }, "respuesta_correcta": "d" },
      { "id": 13, "pregunta": "13. edizioa (2003an)?", "opciones": { "a": "Donibane Garazi-Gasteiz", "b": "Arantzazu-Bilbo", "c": "Gasteiz-Baiona", "d": "Maule-Iruñea" }, "respuesta_correcta": "d" },
      { "id": 14, "pregunta": "14. edizioa (2005ean)?", "opciones": { "a": "Gasteiz-Baiona", "b": "Orreaga-Bilbo", "c": "Karrantza-Iruñea", "d": "Tutera-Gasteiz" }, "respuesta_correcta": "b" },
      { "id": 15, "pregunta": "15. edizioa (2007an)?", "opciones": { "a": "Karrantza-Iruñea", "b": "Orreaga-Bilbo", "c": "Tutera-Gasteiz", "d": "Maule-Iruñea" }, "respuesta_correcta": "a" },
      { "id": 16, "pregunta": "16. edizioa (2009an)?", "opciones": { "a": "Trebiñu-Donostia", "b": "Tutera-Gasteiz", "c": "Andoain-Baiona", "d": "Karrantza-Iruñea" }, "respuesta_correcta": "b" },
      { "id": 17, "pregunta": "17. edizioa (2011n)?", "opciones": { "a": "Orreaga-Bilbo", "b": "Maule-Iruñea", "c": "Trebiñu-Donostia", "d": "Urepele-Bilbo" }, "respuesta_correcta": "c" },
      { "id": 18, "pregunta": "18. edizioa (2013an)?", "opciones": { "a": "Urepele-Bilbo", "b": "Karrantza-Iruñea", "c": "Tutera-Gasteiz", "d": "Andoain-Baiona" }, "respuesta_correcta": "d" },
      { "id": 19, "pregunta": "19. edizioa (2015ean)?", "opciones": { "a": "Otxandio-Iruñea", "b": "Andoain-Baiona", "c": "Otxandio-Iruñea", "d": "Urepele-Bilbo" }, "respuesta_correcta": "d" },
      { "id": 20, "pregunta": "20. edizioa (2017an)?", "opciones": { "a": "Otxandio-Iruñea", "b": "Amurrio-Donostia", "c": "Gares-Gasteiz", "d": "Urepele-Bilbo" }, "respuesta_correcta": "a" },
      { "id": 21, "pregunta": "21. edizioa (2019an)?", "opciones": { "a": "Gares-Gasteiz", "b": "Otxandio-Iruñea", "c": "Urepele-Bilbo", "d": "Andoain-Baiona" }, "respuesta_correcta": "a" },
      { "id": 22, "pregunta": "22. edizioa (2022an)?", "opciones": { "a": "Irun-Baiona", "b": "Gares-Gasteiz", "c": "Irun-Baiona", "d": "Amurrio-Donostia" }, "respuesta_correcta": "d" },
      { "id": 23, "pregunta": "23. edizioa (2024an)?", "opciones": { "a": "Andoain-Baiona", "b": "Urepele-Bilbo", "c": "Amurrio-Donostia", "d": "Irun-Baiona" }, "respuesta_correcta": "d" },
      { "id": 24, "pregunta": "24. edizioa (2026an)?", "opciones": { "a": "Trebiñu-Donostia", "b": "Atharratze-Bilbo", "c": "Gares-Gasteiz", "d": "Irun-Baiona" }, "respuesta_correcta": "b" },
      {"id":25,"pregunta":"Zenbat aldiz hasi da Korrika Atharratzen?","opciones":{"a":"Inoiz ez","b":"Behin soilik, 2026an","c":"Bitan","d":"Hasi behin eta bukatu beste behin"},"respuesta_correcta":"c"},
      {"id":26,"pregunta":"Zein ediziotan izan zen Iruñea hasiera eta bukaera Donostia?","opciones":{"a":"3., 9. eta 10. edizioetan","b":"2., 8. eta 15. edizioetan","c":"3., 8. eta 13. edizioetan","d":"2., 6. eta 11. edizioetan"},"respuesta_correcta":"d"},
      {"id":27,"pregunta":"Zenbat aldiz bukatu zen Korrika Gasteizen 80ko hamarkadan?","opciones":{"a":"Behin","b":"Bi aldiz","c":"Inoiz ez","d":"Bukatu ez, baina hasi behin"},"respuesta_correcta":"c"},
      {"id":28,"pregunta":"Zenbat aldiz bukatu zen Korrika Bilbon 80ko hamarkadan?","opciones":{"a":"Inoiz ez, soilik hasi","b":"Bitan","c":"Hirutan","d":"Behin"},"respuesta_correcta":"c"},
      {"id":29,"pregunta":"Zenbat aldiz hasi da Korrika Donibane-Lohitzunen?","opciones":{"a":"Behin soilik","b":"Hirutan","c":"Inoiz ez","d":"Bitan"},"respuesta_correcta":"c"},
      {"id":30,"pregunta":"Lehen edizioa kontuan hartu gabe, noiz hasi zen Korrika herri batean hasten?","opciones":{"a":"1995ean","b":"1993an","c":"1997an","d":"1999an"},"respuesta_correcta":"c"}
    ]
  },
   ]
